using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using WebApi.Configuration;
using WebApi.Data;

// disabled to avoid no xml docs on injected services as parameters
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)

namespace WebApi.Controllers.Core;

/// <summary>
/// ***Endpoints for testing and troubleshooting the API, included/registered services, configuration, and health status(es)***.
/// </summary>
[ApiController]
[Route("api/v1/debug")]
[Produces("application/json")]
public class DebugController : ControllerBase
{
#region AI Testing
    /// <summary>
    /// AI Health Check
    /// </summary>
    /// <response code="200">AI service is reachable and responding.</response>
    /// <response code="503">AI service connection failed or unavailable.</response>
    /// <remarks>
    /// Tests the connection to Azure OpenAI by making a simple test call.
    /// </remarks>
    [HttpGet("ai/connection")]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(object), StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> TestAiConnection(
        [FromServices] IChatClient chatClient,
        [FromServices] ILogger<DebugController> logger)
    {
        try
        {
            const string testPrompt = "Say 'AI connection successful' in exactly those words, nothing else.";

            var agent = new ChatClientAgent(chatClient, "You are a helpful assistant.");
            var messages = new List<ChatMessage>
            {
                new(ChatRole.User, testPrompt)
            };

            var response = await agent.RunAsync(messages, cancellationToken: HttpContext.RequestAborted);
            var responseText = response.Text ?? string.Empty;

            logger.LogInformation("AI connection test successful. Response received: {Response}", responseText);

            return Ok(new
            {
                status = "connected",
                message = "Successfully reached AI service",
                response = responseText,
                timestamp = DateTime.UtcNow
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "AI connection test failed");

            return StatusCode(503, new
            {
                status = "disconnected",
                message = "Failed to connect to AI service",
                error = ex.Message,
                timestamp = DateTime.UtcNow
            });
        }
    }

    /// <summary>
    /// AI Sample Request
    /// </summary>
    /// <returns>A programming joke generated by the AI service.</returns>
    /// <response code="200">Joke retrieved successfully.</response>
    /// <response code="503">AI service connection failed or unavailable.</response>
    /// <remarks>
    /// Retrieves a programming joke from the AI model.
    /// </remarks>
    [HttpGet("ai/joke")]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(object), StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> GetAiJoke(
        [FromServices] IChatClient chatClient,
        [FromServices] ILogger<DebugController> logger)
    {
        try
        {
            const string prompt = "Tell me a short programming joke";

            var agent = new ChatClientAgent(chatClient, "You are a helpful assistant that tells jokes.");
            var messages = new List<ChatMessage>
            {
                new(ChatRole.User, prompt)
            };

            var response = await agent.RunAsync(messages, cancellationToken: HttpContext.RequestAborted);
            var joke = response.Text ?? "I couldn't think of a joke right now.";

            logger.LogInformation("AI joke endpoint invoked successfully. Joke length: {Length}", joke.Length);

            return Ok(new
            {
                prompt,
                response = joke,
                timestamp = DateTime.UtcNow
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "AI joke endpoint failed");

            return StatusCode(503, new
            {
                status = "error",
                message = "Failed to get joke from AI service",
                error = ex.Message,
                timestamp = DateTime.UtcNow
            });
        }
    }
#endregion

#region Configuration

    /// <summary>
    /// Retrieve CORS configuration
    /// </summary>
    /// <response code="200">CORS configuration retrieved successfully.</response>
    /// <remarks>
    /// Displays the CORS configuration currently being used by the application.
    /// </remarks>
    [HttpGet("config/cors")]
    public IActionResult GetCorsConfig(
        [FromServices] IConfiguration configuration)
    {
        // Use the exact same logic as Program.cs
        var resolvedOrigins = ServiceConfiguration.GetCorsAllowedOrigins(configuration);

        // Check configuration key for debugging
        var corsOriginsString = configuration["Cors__AllowedOrigins"]
                             ?? Environment.GetEnvironmentVariable("Cors__AllowedOrigins");

        var corsOriginsArray = configuration.GetSection("Cors:AllowedOrigins").Get<string[]>();

        // Get all environment variables that start with "Cors" for debugging
        var allCorsEnvVars = Environment.GetEnvironmentVariables()
            .Cast<System.Collections.DictionaryEntry>()
            .Where(e => e.Key.ToString()?.StartsWith("Cors", StringComparison.OrdinalIgnoreCase) == true)
            .ToDictionary(e => e.Key.ToString()!, e => e.Value?.ToString() ?? "(null)");

        // Build response showing what we found
        var response = new
        {
            corsOriginsString = corsOriginsString ?? "(null)",
            corsOriginsArray = corsOriginsArray ?? Array.Empty<string>(),
            corsOriginsArrayLength = corsOriginsArray?.Length ?? 0,
            environmentVariable = Environment.GetEnvironmentVariable("Cors__AllowedOrigins") ?? "(not set)",
            allCorsEnvironmentVariables = allCorsEnvVars,
            allConfigKeys = new
            {
                corsAllowedOrigins = configuration["Cors__AllowedOrigins"] ?? "(null)",
            },
            resolvedOrigins = resolvedOrigins,
            resolvedOriginsCount = resolvedOrigins.Length,
            willAllowAllOrigins = resolvedOrigins.Length == 0
        };

        return Ok(response);
    }

    /// <summary>
    /// Retrieve Full Configuration
    /// </summary>
    /// <response code="200">Configuration values retrieved successfully.</response>
    /// <remarks>
    /// Returns all configuration values as JSON for debugging purposes.
    /// Intended for development environments to inspect application configuration.
    /// </remarks>
    [HttpGet("config/all")]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    public IActionResult GetAllConfig(
        [FromServices] IConfiguration configuration)
    {
        var configDict = GetConfigurationAsDictionary(configuration);
        return Ok(configDict);
    }

    private static Dictionary<string, object?> GetConfigurationAsDictionary(IConfiguration configuration)
    {
        var result = new Dictionary<string, object?>();

        foreach (var child in configuration.GetChildren())
        {
            result[child.Key] = GetConfigurationValue(child);
        }

        return result;
    }

    private static object? GetConfigurationValue(IConfigurationSection section)
    {
        var children = section.GetChildren().ToList();

        if (children.Count == 0)
        {
            // Leaf node - return the value
            return section.Value;
        }

        // Has children - return as dictionary
        var dict = new Dictionary<string, object?>();
        foreach (var child in children)
        {
            dict[child.Key] = GetConfigurationValue(child);
        }

        // If there's also a value at this level, include it
        if (!string.IsNullOrEmpty(section.Value))
        {
            dict["_value"] = section.Value;
        }

        return dict;
    }

#endregion

#region Health

    /// <summary>
    /// Health status
    /// </summary>
    /// <response code="200">Service is healthy and all dependencies are operational.</response>
    /// <response code="503">Service is unhealthy or dependencies are unavailable.</response>
    /// <remarks>
    /// Retrieves detailed health status of the API and its dependencies.
    /// </remarks>
    [HttpGet("health")]
    [ProducesResponseType(typeof(HealthStatus), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(HealthStatus), StatusCodes.Status503ServiceUnavailable)]
    public async Task<ActionResult<HealthStatus>> GetHealth(
        [FromServices] AppDbContext context,
        [FromServices] ILogger<DebugController> logger)
    {
        var health = new HealthStatus
        {
            Status = "Healthy",
            Timestamp = DateTime.UtcNow,
            Version = GetType().Assembly.GetName().Version?.ToString() ?? "Unknown"
        };

        // Check database connectivity
        try
        {
            if (context.Database.IsRelational())
            {
                var canConnect = await context.Database.CanConnectAsync();
                health.Database = new DatabaseHealth
                {
                    Status = canConnect ? "Connected" : "Disconnected",
                    Provider = context.Database.ProviderName ?? "Unknown"
                };
            }
            else
            {
                health.Database = new DatabaseHealth
                {
                    Status = "InMemory",
                    Provider = "InMemory"
                };
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Database health check failed");
            health.Database = new DatabaseHealth
            {
                Status = "Error",
                Provider = context.Database.ProviderName ?? "Unknown",
                Error = ex.Message
            };
            health.Status = "Unhealthy";
        }

        // Determine overall status
        if (health.Status == "Unhealthy" ||
            (health.Database != null && health.Database.Status == "Error"))
        {
            return StatusCode(503, health);
        }

        return Ok(health);
    }

#endregion
}

/// <summary>
/// Health status response model
/// </summary>
public class HealthStatus
{
    public string Status { get; set; } = string.Empty;
    public DateTime Timestamp { get; set; }
    public string Version { get; set; } = string.Empty;
    public DatabaseHealth? Database { get; set; }
}

/// <summary>
/// Database health information
/// </summary>
public class DatabaseHealth
{
    public string Status { get; set; } = string.Empty;
    public string Provider { get; set; } = string.Empty;
    public string? Error { get; set; }
}
