using Microsoft.Agents.AI.DevUI;
using Microsoft.EntityFrameworkCore;
using WebApi.Configuration;
using WebApi.Data;
using WebApi.Middleware;

var builder = WebApplication.CreateBuilder(args);
builder.Services
    .AddControllers()
    .AddJsonOptions(ServiceConfiguration.ConfigureJsonCallback);
builder.Services
    .AddHealthChecks()
    .AddDbContextCheck<AppDbContext>();

var corsEnabled = builder.Services.ConfigureCors(builder.Configuration);
builder.Services.ConfigureAppOptions(builder.Configuration);
builder.Services.ConfigureEmail(builder.Configuration);
builder.Services.ConfigureOpenApi(builder.Configuration);
builder.Services.ConfigureDatabase(builder.Configuration, builder.Environment);
builder.Services.AddDataProtection();
builder.Services.ConfigureJwtAuth(builder.Configuration, builder.Environment);
builder.Services.ConfigureRateLimiting(builder.Configuration);
builder.Services.ConfigureRequestLimits(builder.Configuration);
// builder.Services.ConfigureResponseCompression(builder.Environment);
// builder.Services.ConfigureResponseCaching(builder.Environment);
builder.Services.ConfigureAuthServices(builder.Configuration);
builder.Services.AddHttpContextAccessor();

builder.WebHost.ConfigureKestrel(o => o.AllowSynchronousIO = true);

// ai shit
builder.Services.ConfigureCoreAiAgents(builder.Configuration);

var app = builder.Build();

// validate options on startup -> fast fail
ValidateConfigurationOnStartup(app.Services, app.Environment, app.Logger);

// request/response logging, must be before GlobalExceptionHandlerMiddleware so it can capture error responses
// DISABLED: Buffers entire response, breaks streaming
// app.UseMiddleware<RequestLoggingMiddleware>();

// global unhandled exception handling (should be early in pipeline, after logging)
// DISABLED: Buffers response, breaks streaming
// app.UseMiddleware<GlobalExceptionHandlerMiddleware>();

// middleware for security response security headers
app.UseMiddleware<SecurityHeadersMiddleware>();

app.UseRateLimiter();

if (app.Environment.IsProduction())
{
    // app.UseResponseCompression();
}

// Serve OpenAPI JSON spec for Scalar UI
// The spec is generated by Swashbuckle and consumed by Scalar at /swagger/v1/swagger.json
// In a production environment, consider restricting access to this endpoint
app.UseSwagger();

if (app.Environment.IsProduction())
{
    // app.UseHttpsRedirection();
}

// Routing must come before response caching
app.UseRouting();

if (app.Environment.IsProduction())
{
    // app.UseResponseCaching();
}

if (corsEnabled)
{
    app.UseCors();
}

app.UseAuthentication();
app.UseAuthorization();

app.ConfigureScalarDocs();

app.MapControllers();

// Health check endpoint
app.MapHealthChecks("/health");

// Apply migrations automatically in container/dev environments (safe no-op if already applied).
// This is required for docker-compose scenarios where the DB starts empty.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    var env = services.GetRequiredService<IHostEnvironment>();

    // Only attempt migration if a relational DbContext is registered (tests override this).
    if (!env.IsEnvironment("Test"))
    {
        var db = services.GetService<AppDbContext>();
        if (db != null && db.Database.IsRelational())
        {
            try
            {
                db.Database.Migrate();
            }
            catch (Exception ex) when (ex.Message.Contains("pending changes") ||
                                       ex.Message.Contains("PendingModelChanges"))
            {
                // Migration pending - this is expected during development when model changes haven't been migrated yet
                // In production, migrations should be applied via CI/CD or manual process
            }
        }
    }
}

app.Run();

// Make the implicit Program class public for testing
public partial class Program
{
}
