using Microsoft.EntityFrameworkCore;
using Scalar.AspNetCore;
using WebApi.Configuration;
using WebApi.Data;
using WebApi.Middleware;
using WebApi.Repositories;
using WebApi.Services.AI.Plugins;
using WebApi.Services.AI.Scenarios;
using WebApi.Services.Chat;
using WebApi.Services.VectorStore;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddControllers()
    .AddJsonOptions(ServiceConfiguration.ConfigureJsonCallback);

builder.Services
    .AddHealthChecks()
    .AddDbContextCheck<AppDbContext>();

var corsEnabled = builder.Services.ConfigureCors(builder.Configuration);
builder.Services.ConfigureAppOptions(builder.Configuration);
builder.Services.ConfigureEmail(builder.Configuration);
builder.Services.ConfigureOpenApi(builder.Configuration);
builder.Services.ConfigureDatabase(builder.Configuration, builder.Environment);
builder.Services.AddDataProtection();
builder.Services.ConfigureJwtAuth(builder.Configuration, builder.Environment);
builder.Services.ConfigureRateLimiting(builder.Configuration);
builder.Services.ConfigureRequestLimits(builder.Configuration);
builder.Services.ConfigureResponseCompression(builder.Environment);
builder.Services.ConfigureResponseCaching(builder.Environment);
builder.Services.ConfigureOpenTelemetry(builder.Configuration, builder.Logging, builder.Environment);
builder.Services.ConfigureAuthServices(builder.Configuration);
builder.Services.ConfigureAi();
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ConversationService>();

// Register location service as singleton for caching
builder.Services.AddSingleton<WebApi.Services.Location.LocationService>();

// Health chat repositories
builder.Services.AddScoped<SymptomRepository>();
builder.Services.AddScoped<EpisodeRepository>();
builder.Services.AddScoped<AssessmentRepository>();
builder.Services.AddScoped<NegativeFindingRepository>();
builder.Services.AddScoped<AppointmentRepository>();
builder.Services.AddScoped<VectorStoreRepository>();

// Health chat services
builder.Services.AddScoped<VectorStoreService>();
builder.Services.AddScoped<ConversationContextService>();
builder.Services.AddScoped<SymptomTrackerPlugin>();
builder.Services.AddScoped<AssessmentPlugin>();
builder.Services.AddScoped<HealthChatScenario>();
builder.Services.AddScoped<ResponseRouterService>();
builder.Services.AddScoped<HealthChatOrchestrator>();
builder.Services.AddScoped<WebApi.Services.Graph.GraphDataService>();

// SignalR
builder.Services.AddSignalR();
builder.Services.AddScoped<IStatusUpdateService, StatusUpdateService>();

var app = builder.Build();

// validate options on startup -> fast fail
ValidateConfigurationOnStartup(app.Services, app.Environment, app.Logger);

// request/response logging, must be before GlobalExceptionHandlerMiddleware so it can capture error responses
app.UseMiddleware<RequestLoggingMiddleware>();

// global unhandled exception handling (should be early in pipeline, after logging)
app.UseMiddleware<GlobalExceptionHandlerMiddleware>();

// middleware for security response security headers
app.UseMiddleware<SecurityHeadersMiddleware>();

app.UseRateLimiter();

if (app.Environment.IsProduction())
{
    app.UseResponseCompression();
}

// Serve OpenAPI JSON spec for Scalar UI
// The spec is generated by Swashbuckle and consumed by Scalar at /swagger/v1/swagger.json
// In a production environment, consider restricting access to this endpoint
app.UseSwagger();

if (app.Environment.IsProduction())
{
    app.UseHttpsRedirection();
}

// Routing must come before response caching
app.UseRouting();

if (app.Environment.IsProduction())
{
    app.UseResponseCaching();
}

if (corsEnabled)
{
    app.UseCors();
}

app.UseAuthentication();
app.UseAuthorization();

// Map Scalar UI - modern API documentation interface
// Consumes the OpenAPI spec served at /swagger/v1/swagger.json
app.MapScalarApiReference(options =>
{
    options.WithTheme(ScalarTheme.None); // Start fresh to apply custom theme
    options.WithOpenApiRoutePattern("/swagger/v1/swagger.json");
    options.WithTitle("API Documentation");
    options.WithDefaultFonts(false); // Use custom fonts
    
    // Match frontend theme: dark theme with Inter font and blue accent (#5288ed)
    options.WithCustomCss(@"
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        
        :root {
            --scalar-font: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            --scalar-font-code: 'Inter', 'Courier New', monospace;
            
            /* Text colors - matching frontend foreground (oklch(0.985 0 0)) */
            --scalar-color-1: #fafafa;
            --scalar-color-2: #d4d4d4;
            --scalar-color-3: #a3a3a3;
            
            /* Accent color - matching frontend blue (#5288ed) */
            --scalar-color-accent: #5288ed;
            
            /* Backgrounds - matching frontend dark theme */
            /* Background: oklch(0.141 0.005 285.823) ≈ #1a1a1a */
            --scalar-background-1: #0f0f0f;
            --scalar-background-2: #1a1a1a;
            /* Card: oklch(0.21 0.006 285.885) ≈ #2a2a2a */
            --scalar-background-3: #2a2a2a;
            
            /* Borders - matching frontend border (rgba white 0.1) */
            --scalar-border-color: rgba(255, 255, 255, 0.1);
            
            /* Button/input backgrounds */
            --scalar-button-1: #2a2a2a;
            --scalar-button-1-hover: #353535;
            --scalar-button-1-color: #fafafa;
            
            /* Code blocks */
            --scalar-code-background: #1a1a1a;
            --scalar-code-color: #fafafa;
            
            /* Muted/secondary colors */
            --scalar-color-muted: #404040;
            --scalar-color-muted-foreground: #a3a3a3;
        }
    ");

    options.DotNetFlag = true;
    options.HideClientButton = true;
});
app.MapGet("/", () => Results.Redirect("/scalar", permanent: false))  // root redirect to Scalar UI
    .ExcludeFromDescription()
    .WithName("RootRedirect")
    .WithTags("Redirect");

app.MapControllers();

// SignalR hub
app.MapHub<WebApi.Hubs.ChatHub>("/hubs/chat");

// Health check endpoint
app.MapHealthChecks("/health");

// Apply migrations automatically in container/dev environments (safe no-op if already applied).
// This is required for docker-compose scenarios where the DB starts empty.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    var env = services.GetRequiredService<IHostEnvironment>();

    // Only attempt migration if a relational DbContext is registered (tests override this).
    if (!env.IsEnvironment("Test"))
    {
        var db = services.GetService<AppDbContext>();
        if (db != null && db.Database.IsRelational())
        {
            try
            {
                db.Database.Migrate();
            }
            catch (Exception ex) when (ex.Message.Contains("pending changes") ||
                                       ex.Message.Contains("PendingModelChanges"))
            {
                // Migration pending - this is expected during development when model changes haven't been migrated yet
                // In production, migrations should be applied via CI/CD or manual process
            }
        }
    }
}

app.Run();

// Make the implicit Program class public for testing
public partial class Program
{
}
