using Microsoft.Agents.AI.DevUI;
using Microsoft.Agents.AI.Hosting;
using Microsoft.EntityFrameworkCore;
using WebApi.Configuration;
using WebApi.Data;
using WebApi.Middleware;
using WebApi.Repositories;
using WebApi.Services.AI.Scenarios;
using WebApi.Services.Chat;
using WebApi.Services.Chat.Conversations;
using WebApi.Services.VectorStore;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddControllers()
    .AddJsonOptions(ServiceConfiguration.ConfigureJsonCallback);

builder.Services
    .AddHealthChecks()
    .AddDbContextCheck<AppDbContext>();

builder.AddDevUI();

var corsEnabled = builder.Services.ConfigureCors(builder.Configuration);
builder.Services.ConfigureAppOptions(builder.Configuration);
builder.Services.ConfigureEmail(builder.Configuration);
builder.Services.ConfigureOpenApi(builder.Configuration);
builder.Services.ConfigureDatabase(builder.Configuration, builder.Environment);
builder.Services.AddDataProtection();
builder.Services.ConfigureJwtAuth(builder.Configuration, builder.Environment);
builder.Services.ConfigureRateLimiting(builder.Configuration);
builder.Services.ConfigureRequestLimits(builder.Configuration);
builder.Services.ConfigureResponseCompression(builder.Environment);
builder.Services.ConfigureResponseCaching(builder.Environment);
builder.Services.ConfigureOpenTelemetry(builder.Configuration, builder.Logging, builder.Environment);
builder.Services.ConfigureAuthServices(builder.Configuration);
var agentBuilders = builder.ConfigureAi();
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ConversationService>();

// Register location service as singleton for caching
builder.Services.AddSingleton<WebApi.Services.Location.LocationService>();

// Health chat repositories
builder.Services.AddScoped<SymptomRepository>();
builder.Services.AddScoped<EpisodeRepository>();
builder.Services.AddScoped<AssessmentRepository>();
builder.Services.AddScoped<NegativeFindingRepository>();
builder.Services.AddScoped<AppointmentRepository>();
builder.Services.AddScoped<VectorStoreRepository>();

// Health chat services
builder.Services.AddScoped<VectorStoreService>();
builder.Services.AddScoped<ConversationContextService>();
builder.Services.AddScoped<HealthChatScenario>();
builder.Services.AddScoped<ResponseRouterService>();
builder.Services.AddScoped<StatusInformationSerializer>();
builder.Services.AddScoped<EntityChangeTracker>();
builder.Services.AddScoped<HealthChatOrchestrator>();
builder.Services.AddScoped<WebApi.Services.Graph.GraphDataService>();

// SignalR
builder.Services.AddSignalR();

var app = builder.Build();

// validate options on startup -> fast fail
ValidateConfigurationOnStartup(app.Services, app.Environment, app.Logger);

// request/response logging, must be before GlobalExceptionHandlerMiddleware so it can capture error responses
app.UseMiddleware<RequestLoggingMiddleware>();

// global unhandled exception handling (should be early in pipeline, after logging)
app.UseMiddleware<GlobalExceptionHandlerMiddleware>();

// middleware for security response security headers
app.UseMiddleware<SecurityHeadersMiddleware>();

app.UseRateLimiter();

if (app.Environment.IsProduction())
{
    app.UseResponseCompression();
}

// Serve OpenAPI JSON spec for Scalar UI
// The spec is generated by Swashbuckle and consumed by Scalar at /swagger/v1/swagger.json
// In a production environment, consider restricting access to this endpoint
app.UseSwagger();

if (app.Environment.IsProduction())
{
    app.UseHttpsRedirection();
}


// Routing must come before response caching
app.UseRouting();

if (app.Environment.IsProduction())
{
    app.UseResponseCaching();
}

if (corsEnabled)
{
    app.UseCors();
}

app.UseAuthentication();
app.UseAuthorization();

app.ConfigureScalarDocs();

app.MapControllers();

app.MapDevUI();

// Map agent endpoints for DevUI and API access
app.MapOpenAIChatCompletions(agentBuilders.HealthChatAgent);
app.MapOpenAIChatCompletions(agentBuilders.AssessmentWorkflowAgent);
app.MapOpenAIChatCompletions(agentBuilders.SymptomTrackingWorkflowAgent);

// Map agent discovery endpoint for DevUI
app.MapAgentDiscovery("/agents");

// SignalR hub
app.MapHub<WebApi.Hubs.ChatHub>("/hubs/chat");

// Health check endpoint
app.MapHealthChecks("/health");

// Apply migrations automatically in container/dev environments (safe no-op if already applied).
// This is required for docker-compose scenarios where the DB starts empty.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    var env = services.GetRequiredService<IHostEnvironment>();

    // Only attempt migration if a relational DbContext is registered (tests override this).
    if (!env.IsEnvironment("Test"))
    {
        var db = services.GetService<AppDbContext>();
        if (db != null && db.Database.IsRelational())
        {
            try
            {
                db.Database.Migrate();
            }
            catch (Exception ex) when (ex.Message.Contains("pending changes") ||
                                       ex.Message.Contains("PendingModelChanges"))
            {
                // Migration pending - this is expected during development when model changes haven't been migrated yet
                // In production, migrations should be applied via CI/CD or manual process
            }
        }
    }
}

app.Run();

// Make the implicit Program class public for testing
public partial class Program
{
}
